///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace azure_trial
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
          /// <summary>
          ///The Recording1 recording.
          /// </summary>
          [TestModule("80d5eb95-2f2f-4ca5-ba30-47576b7e71c9", ModuleType.Recording, 1)]
          public partial class Recording1 : ITestModule
          {
                    /// <summary>
                    /// Holds an instance of the azure_trialRepository repository.
                    /// </summary>
                    public static azure_trialRepository repo = azure_trialRepository.Instance;

                    static Recording1 instance = new Recording1();

                    /// <summary>
                    /// Constructs a new instance.
                    /// </summary>
                    public Recording1()
                    {
                    }

                    /// <summary>
                    /// Gets a static instance of this recording.
                    /// </summary>
                    public static Recording1 Instance
                    {
                              get { return instance; }
                    }

#region Variables

#endregion

                    /// <summary>
                    /// Starts the replay of the static recording <see cref="Instance"/>.
                    /// </summary>
                    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
                    public static void Start()
                    {
                              TestModuleRunner.Run(Instance);
                    }

                    /// <summary>
                    /// Performs the playback of actions in this recording.
                    /// </summary>
                    /// <remarks>You should not call this method directly, instead pass the module
                    /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
                    /// that will in turn invoke this method.</remarks>
                    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
                    void ITestModule.Run()
                    {
                              Mouse.DefaultMoveTime = 300;
                              Keyboard.DefaultKeyPressTime = 20;
                              Delay.SpeedFactor = 1.00;

                              Init();

                              Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'test' on item 'RxMainFrame.EnterYourName'.", repo.RxMainFrame.EnterYourNameInfo, new RecordItemIndex(0));
                              repo.RxMainFrame.EnterYourName.Element.SetAttributeValue("Text", "test");
                              Delay.Milliseconds(0);
                              
                              Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.BtnSubmitUserName' at Center.", repo.RxMainFrame.BtnSubmitUserNameInfo, new RecordItemIndex(1));
                              repo.RxMainFrame.BtnSubmitUserName.Click();
                              Delay.Milliseconds(0);
                              
                              Report.Log(ReportLevel.Info, "User", "Done", new RecordItemIndex(2));
                              
                    }

#region Image Feature Data
#endregion
          }
#pragma warning restore 0436
}
